[package]
name = "ochd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.9.0"
tiny-skia-path = "0.9.0"
resvg = "0.32.0"
fn_graph = { version = "0.8.2" }
smallvec = "1.10.0"
usvg = "0.32.0"
anyhow = "1.0"
cached = "0.43.0"
ordered-float = "3.7.0"
lazy_static = "1.4.0"
const_format = {version = "0.2.30", features = ["fmt", "rust_1_64"]}
rayon = "1.7.0"
petgraph = "0.6.3"
logging-allocator = "0.1.1"
simple-logging = "2.0.2"
log = "0.4.17"
tracing = {version = "0.1.38", features = ["attributes"]}
itertools = "0.10.5"
replace_with = "0.1.7"
once_cell = "1.17.1"
lockfree-object-pool = "0.1.4"
png = "0.17.8"
pathdiff = "0.2.1"
tokio = {version = "1.28.0", features = ["rt-multi-thread", "macros"]}
tikv-jemallocator = "0.5.0"
zip_next = {version = "0.6.7"}
num_cpus = "1.15.0"