[package]
name = "OcHd-RustBuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.8.3"
tiny-skia-path = "0.8.3"
resvg = "0.30.0"
futures = "0.3"
fn_graph = { version = "0.8.1", features = ["fn_meta", "resman"] }
resman = { version = "0.16.0", features = ["fn_res", "fn_meta"] }
fn_meta = "0.7.3"
smallvec = "1.10.0"
usvg = "0.30.0"
anyhow = "1.0"
cached = "0.42.0"
ordered-float = "3.6.0"
lazy_static = "1.4.0"
strum = "0.24.1"
const_format = {version = "0.2.30", features = ["fmt", "rust_1_64"]}
threadpool = "1.8.1"
num_cpus = "1.15.0"
weak-table = "0.3.2"
chashmap-next = "2.2.3"
async-std = {version = "1.12.0", features = ["unstable"]}
tokio = {version = "1.27.0", features = ["rt", "rt-multi-thread", "sync"]}
async-recursion = "1.0.4"
