[package]
name = "OcHd-RustBuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.8.3"
tiny-skia-path = "0.8.3"
resvg = "0.30.0"
futures = "0.3"
rgraph = "0.2.2"
usvg = "0.30.0"
anyhow = "1.0"
cached = "0.42.0"
ordered-float = "3.6.0"
