[package]
name = "OcHd-RustBuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.8.3"
tiny-skia-path = "0.8.3"
resvg = "0.30.0"
futures = "0.3"
daggy = "0.8.0"
async_dag = "0.1.2"
usvg = "0.30.0"
anyhow = "1.0"
cached = "0.42.0"
ordered-float = "3.6.0"
lazy_static = "1.4.0"
strum = "0.24.1"
const_format = {version = "0.2.30", features = ["fmt", "rust_1_64"]}
