[package]
name = "OcHd-RustBuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.8.3"
tiny-skia-path = "0.8.3"
resvg = "0.30.0"
fn_graph = { version = "0.8.1", features = ["fn_meta", "resman"] }
resman = { version = "0.16.0", features = ["fn_res", "fn_meta"] }
fn_meta = "0.7.3"
smallvec = "1.10.0"
usvg = "0.30.0"
anyhow = "1.0"
cached = "0.42.0"
ordered-float = "3.6.0"
lazy_static = "1.4.0"
const_format = {version = "0.2.30", features = ["fmt", "rust_1_64"]}
rayon = "1.7.0"
petgraph = "0.6.3"
logging-allocator = "0.1.1"
simple-logging = "2.0.2"
log = "0.4.17"
tracing = {version = "0.1.37", features = ["attributes"]}
itertools = "0.10.5"
replace_with = "0.1.7"
once_cell = "1.17.1"