[package]
name = "ochd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.34.1"
anyhow = "1.0.71"
cached = "0.43.0"
ordered-float = "3.7.0"
lazy_static = "1.4.0"
const_format = {version = "0.2.31", features = ["fmt", "rust_1_64"]}
rayon = "1.7.0"
simple-logging = "2.0.2"
log = "0.4.18"
itertools = "0.10.5"
replace_with = "0.1.7"
lockfree-object-pool = "0.1.4"
png = "0.17.8"
include_dir = "0.7.3"
tikv-jemallocator = "0.5.0"
zip_next = {version = "0.10.0", default-features = false, features = ["deflate-zlib-ng", "deflate-zopfli"]}
oxipng = {git = "https://github.com/shssoichiro/oxipng.git", default-features = false, features = ["zopfli"]}
bitstream-io = "1.6.0"
palette = "0.7.2"
bytemuck = {version = "1.13.1", features = ["derive"]}

[dev-dependencies]
tiny-skia-path = "0.10.0"
